@startuml
left to right direction

:Người dùng: as user
:Khách: as guest
:Người dùng ẩn danh: as anonymous

'note'

package "Xác thực người dùng"{
	usecase googleSignin as "Đăng nhập bằng Google"
	usecase anonymousSignin as "Đăng nhập ẩn danh"
}

package "Quản lí phiên"{
	usecase logout as "Đăng xuất"

}

package "Quản lí tài khoản"{
	usecase viewProfile as "Hiển thị hồ sơ"
	usecase updateProfile as "Cập nhật hồ sơ"
}

user-|>anonymous

anonymous-->logout
anonymous-->viewProfile
anonymous-->updateProfile
anonymous-->(Liên kết Google)

guest-->anonymousSignin
guest-->googleSignin

newpage
(Cập nhật hồ sơ) ..>(Hiển thị hồ sơ) :<<include>>

(Đăng nhập ẩn danh) ..>(Xác thực người dùng):<<extend>>
(Đăng nhập bằng Google) ..>(Xác thực người dùng):<<extend>>

@enduml

