@startuml
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 15

|Khách|
start
:Click "Đăng nhập khách";
|Ứng dụng|
:Gửi yêu cầu đăng nhập khách;
|Firebase|
if (Thành \n công?) then (Có)
  :Tạo UID  tạm thời;
  :Trả về phiên \n đăng nhập;
  |Ứng dụng|
  :Chuyển đến màn hình chính;
else (Lỗi)
  |Firebase|
  :Trả về thông báo lỗi;
  |Ứng dụng|
  :Hiển thị thông báo lỗi;
endif

stop
@enduml