@startuml
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 30

|Người dùng|
: Mở màn hình "Công thức của tôi";

|Lớp biểu diễn|
: Gọi lớp nghiệp vụ để tải danh sách công thức;

|Lớp nghiệp vụ|
: Gọi lớp dữ liệu để lấy dữ liệu;

|Lớp dữ liệu|
: Truy vấn csdl và sắp xếp dữ liệu;
: Trả về danh sách công thức;

|Lớp nghiệp vụ|
:Áp dụng quy tắc nghiệp vụ;
: Trả dữ liệu cho Lớp biểu diễn;

|Lớp biểu diễn|
: Chuyển đổi thành dữ liệu \nhiển thị ra màn hình;

|Lớp biểu diễn|
if (Có dữ liệu?) then (Có)
  : Hiển thị danh sách công thức;
  note right
    **Mỗi công thức hiển thị:**
    - Tên công thức
    - Ảnh món ăn
    và kèm theo id của công thức
  end note
else (Không có dữ liệu)
  : Hiển thị màn hình trống;
endif

|Người dùng|
: Xem danh sách công thức;
: Chọn một công thức để xem chi tiết;

stop
@enduml