@startuml
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 30
|Người dùng|
start
:Click "Đăng nhập bằng Google";
|Ứng dụng|
:Hiển thị hộp thoại \nchọn tài khoản Google;
|Google|
:Hiển thị danh sách tài khoản;
|Người dùng|
if (Hủy bỏ?) then (Có)
  :Đóng
  hộp thoại;
  |Ứng dụng|
  :Thông báo hủy;
  stop
else (Không)
	|Người dùng|
  :Chọn tài khoản Google;
  |Google|
  :Trả về credential (ID token);
  |Ứng dụng|
  :Gửi credential tới Firebase;
  |Firebase|
  if (Xác thực\n\nthành công?) then (Có)
    |Ứng dụng|
    :Chuyển đến \n màn hình chính;
  else (Lỗi)
    |Ứng dụng|
    :Hiển thị thông báo lỗi;
  endif
endif
stop
@enduml