@startuml
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 30

|Khách|
start
:Click "Liên kết tài khoản tạm thời";
|Ứng dụng|
:Hiển thị hộp thoại \nchọn tài khoản Google;
|Google|
:Hiển thị danh sách tài khoản;
|Khách|
if (Hủy bỏ?) then (Có)
  :Đóng
  hộp thoại;
  |Ứng dụng|
  :Thông báo hủy;
  stop
else (Không)
	|Khách|
  :Chọn tài khoản Google;
  |Google|
  :Trả về credential (ID token);
  |Ứng dụng|
  :Gửi credential tới Firebase;
  |Firebase|
  if (Liên kết\n\nthành công?) then (Có)
    |Ứng dụng|
    :Cập nhật hồ sơ \ncủa người dùng;
  else (Lỗi)
    |Ứng dụng|
    :Hiển thị thông báo lỗi;
  endif
endif
stop
@enduml