@startuml
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 15

|Người dùng|
:Click "Đăng xuất";
|Ứng dụng|
if (Là tài khoản ẩn danh?) then (Có)
  |Firebase|
  :Xóa tài khoản \nẩn danh;
  |Ứng dụng|
else (Không)
  |Ứng dụng|
endif
  :Đăng xuất khỏi thiết bị;

|Firebase|
:Huỷ phiên đăng nhập;
|Ứng dụng|
:Xoá dữ liệu local;
:Chuyển đến màn hình đăng nhập;
|Người dùng|
:Nhìn thấy màn hình đăng nhập;

stop
@enduml