@startuml
left to right direction
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 13

:Người dùng: as user
:Khách: as guest
:Người dùng ẩn danh: as anonymous

'note'
rectangle {
	usecase googleSignin as "Đăng nhập bằng Google"
	usecase anonymousSignin as "Đăng nhập ẩn danh"
	usecase linkGoogle as "Liên kết Google"
	usecase logout as "Đăng xuất"
	usecase viewProfile as "Hiển thị hồ sơ"
	usecase updateProfile as "Cập nhật hồ sơ"
	}

user---logout
user---viewProfile
user---updateProfile

anonymous--logout
anonymous--linkGoogle

guest --anonymousSignin
guest --googleSignin

updateProfile -l..>viewProfile:<<include>>

newpage
skinparam DefaultFontName "Liberation Serif"
skinparam DefaultFontSize 15
left to right direction
:Người dùng: as user
:Người dùng ẩn danh: as anonymous

rectangle {
	usecase manage_ingredient as "Quản lí nguyên liệu"
	usecase manage_instruction as "Quản lí bước làm"
	usecase manage_recipe as "Quản lí công thức"
	usecase upload_recipe as "Chia sẻ công thức"
	usecase rate_recipe as "Đánh giá công thức"
	usecase like_recipe as "Yêu thích công thức"
}

anonymous --manage_ingredient
anonymous --manage_instruction
anonymous ---manage_recipe

user ---manage_ingredient
user ---manage_instruction
user ---manage_recipe
user ---upload_recipe
user --rate_recipe
user --like_recipe


note right of (manage_ingredient)
	Thêm/Xem
	/Sửa/Xoá
end note

note right of (manage_recipe)
	Thêm/Xem
	/Sửa/Xoá
end note

note right of (manage_instruction)
	Thêm/Xem
	/Sửa/Xoá
end note

newpage
left to right direction

(Thêm bước làm)..>(Thêm công thức):<<include>>
(Thêm bước làm)..>(Chụp ảnh bước làm):<<include>>
(Thêm nguyên liệu)..>(Thêm công thức):<<include>>

(Thêm công thức)..>(Chụp ảnh món ăn):<<include>>

(Xem chi tiết công thức)..>(Xem danh sách bước):<<include>>
(Xem chi tiết công thức)..>(Xem danh sách nguyên liệu):<<include>>

(Xoá công thức)..>(Xoá bước làm):<<include>>
(Xoá công thức)..>(Xoá nguyên liệu):<<include>>

@enduml

